create table user (id varchar(255) not null, created_at date, email varchar(255), is_admin boolean, name varchar(255), password varchar(255), primary key (id))
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id varchar(255) not null, created_at date, email varchar(255), is_admin boolean, name varchar(255), password varchar(255), primary key (id))
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id varchar(255) not null, created_at date, email varchar(255), is_admin boolean, name varchar(255), password varchar(255), primary key (id))
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table user (id varchar(255) not null, created_at date, email varchar(255), is_admin boolean, name varchar(255), password varchar(255), primary key (id))
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email)
create table euser (id varchar(255) not null, created_at date, email varchar(255), is_admin boolean, name varchar(255), password varchar(255), primary key (id))
alter table euser add constraint UK_9ukgx8abe7sku5ccyrmrk7lak unique (email)
